SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke(){
            return View(cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent:ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke() {
           
           //unuse atm
            //ViewBag.SelectedCategory = ViewContext.RouteData.Values["category"];
            
            //ViewContext.RouteData?.Values["category"];
            return View(repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x));
            //return "Hello from the Nav View Component";
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card m-1 p-1" style="background-color: transparent;border-color: #0275d8;">
    <div class="bg-light p-1">
        <h4>@Model.Name
        <span class="badge-pill badge-primary" style="float:right">
            <small>@Model.Price.ToString("c")
            </small>
            </span>      
            </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">@Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Add To Cart</button>
        </span>
    </form>
    
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link asp-href-include="~/lib/bootstrap/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*grid*" rel="stylesheet" />
    <link asp-href-include="~/lib/fontawesome-free/css/*.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-dark" role="navigation">
        <div class="row">
        <a class="col navbar-brand" href="#">SPORTS STORE</a>
        <div class="col-6 text-right">@await Component.InvokeAsync("CartSummary")</div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-2">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-10">
            @RenderBody()
        </div>
    </div>
</body>
</html>